[package]
name = "include-idl-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
goblin = { version = "0.8.2" }
include-idl = { path = "../include-idl", features = ["parse"] }
